version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:13.4
    environment:
      POSTGRES_USER: rainbow
      POSTGRES_PASSWORD: 911
      POSTGRES_DB: rainbow
    volumes:
      - type: bind
        source: ./src/db/init-dev.sql
        target: /docker-entrypoint-initdb.d/init-dev.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.0
    environment:
      PGADMIN_DEFAULT_EMAIL: emils@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 911
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - type: bind
        source: /data/pgadmin4
        target: /var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  redis:
    container_name: redis_container
    image: redis:6.2.5
    volumes:
      - type: bind
        source: /data/redis-rainbow
        target: /data
    ports:
      - "6379:6379"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge